logging:
  level: INFO
  loggers:
    com.cmontilha: DEBUG

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:budget;MODE=MYSQL;DB_CLOSE_DELAY=-1
  user: sa
  password: ""
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: update
