logging:
  level: INFO
  loggers:
    com.cmontilha: DEBUG

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:budgetdb;MODE=MYSQL;DB_CLOSE_DELAY=-1
  user: sa
  password: ""
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: update
    hibernate.bytecode.use_reflection_optimizer: false
    hibernate.enable_lazy_load_no_trans: true
